name: Test, Publish, & Release
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn install 
      - run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
